"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# -----------------------------------------
# SUPERUSER ENV MAPPING (REQUIRED)
# -----------------------------------------
os.environ.setdefault('DJANGO_SUPERUSER_USERNAME', os.getenv('ADMIN_USERNAME', 'admin'))
os.environ.setdefault('DJANGO_SUPERUSER_EMAIL', os.getenv('ADMIN_EMAIL', 'admin@example.com'))
os.environ.setdefault('DJANGO_SUPERUSER_PASSWORD', os.getenv('ADMIN_PASSWORD', 'admin123'))

try:
    import cloudinary
except ModuleNotFoundError:
    cloudinary = None

BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-$kc!20r!1&kkdoq!rpne9ru+j$1e5d#edf5s-&ujgwi+xt=2+-'
)

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [
    h.strip() for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',') if h.strip()
]

# HTTPS / CSRF (required for POST on Render and other reverse proxies)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

_csrf_origins = [
    o.strip() for o in config('CSRF_TRUSTED_ORIGINS', default='').split(',') if o.strip()
]
_render_public = (os.environ.get('RENDER_EXTERNAL_URL') or '').rstrip('/')
if _render_public and _render_public not in _csrf_origins:
    _csrf_origins.append(_render_public)
CSRF_TRUSTED_ORIGINS = _csrf_origins


# APPLICATIONS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',

]

if cloudinary is not None:
    INSTALLED_APPS += [
        'cloudinary',
        'cloudinary_storage',
    ]

# Resend (HTTPS) — use on Render free tier; outbound SMTP ports are blocked there.
RESEND_API_KEY = (os.getenv('RESEND_API_KEY') or '').strip() or None
if RESEND_API_KEY:
    INSTALLED_APPS += ['anymail']


# MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# DATABASE
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use PostgreSQL in production
if not DEBUG:
    DATABASES['default'] = dj_database_url.config(
        default=config('DATABASE_URL')
    )


# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# STATIC FILES
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# CLOUDINARY (MEDIA)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

# Default local media storage (used in local/dev fallback)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if cloudinary is not None and all(CLOUDINARY_STORAGE.values()):
    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
        api_key=CLOUDINARY_STORAGE['API_KEY'],
        api_secret=CLOUDINARY_STORAGE['API_SECRET'],
    )

    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }


# EMAIL CONFIG
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 15

EMAIL_HOST_USER = (os.getenv("EMAIL_HOST_USER") or "").strip() or None
# Gmail app passwords are often pasted with spaces; SMTP requires the 16 chars without spaces.
_raw_mail_pass = os.getenv("EMAIL_HOST_PASSWORD") or ""
EMAIL_HOST_PASSWORD = _raw_mail_pass.replace(" ", "").replace("\t", "") or None

if RESEND_API_KEY:
    # Works on Render free tier (port 443). Get a key at https://resend.com
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
    ANYMAIL = {"RESEND_API_KEY": RESEND_API_KEY}
    # After verifying your domain in Resend, set e.g. DEFAULT_FROM_EMAIL=hello@nishanpaudel.info.np
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="onboarding@resend.dev")
elif DEBUG and not (EMAIL_HOST_USER and EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@example.com"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@example.com"

CONTACT_INBOX = config("CONTACT_INBOX", default="nishan.official22@gmail.com")


# DEFAULT PK
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# So contact-form SMTP errors show in Render / gunicorn logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'portfolio': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}