# Generated by Django 6.0.1 on 2026-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_email_profile_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('link', models.URLField(blank=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
