# Generated by Django 6.0.1 on 2026-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate_created_at_alter_certificate_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_blockchain',
            field=models.BooleanField(default=False),
        ),
    ]
