# Generated by Django 6.0.1 on 2026-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this post from the Web3 / blockchain page.'),
        ),
    ]
